# This is a sample build configuration for JavaScript.
# Check our guides at https://confluence.atlassian.com/x/14UWN for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: node:10.15.3

pipelines:
  default:
    - step:
        caches:
          - node
        script: # Modify the commands below to build your repository.
          - npm install
          - echo 
          - npm run build
          - pipe: atlassian/sftp-deploy:0.5.4
            variables:
              USER: 'Worknests_Server'
              SERVER: '14.140.119.214'
              REMOTE_PATH: '../../sandbox/iBasis/ibasis-frontend'
              LOCAL_PATH: './dist/ibasis-ui'
              PASSWORD: 'WoodPecker@2019' # Optional.
