import { Roles } from 'src/app/core/_models';
import { environment } from 'src/environments/environment';

export class SidenavData {
  sideNav = [
    {
      itemId: 'process',
      itemName: 'Process Explorer',
      itemIconClass: 'fa fa-pie-chart',
      visibleFor: [
        Roles.LEGAL_ADMIN,
        Roles.SUPER_ADMIN,
        Roles.SALES_USER,
        Roles.LEGAL_USER,
        Roles.SYSTEM_ADMIN,
        Roles.BILLING_USER,
        Roles.BILLING_ADMIN,
        Roles.COMMERCIAL_OPS_ADMIN,
        Roles.COMMERCIAL_OPS_USER,
        Roles.CREDIT_ADMIN,
        Roles.CREDIT_USER,
        Roles.FPA_USER,
        Roles.FPA_ADMIN,
        Roles.INTERCONNECT_DESIGN_USER,
        Roles.INTERCONNECT_DESIGN_ADMIN,
        Roles.PRODUCT_MANAGEMENT_USER,
        Roles.PRODUCT_MANAGEMENT_ADMIN,
        Roles.PMIOT_USER,
        Roles.PMIOT_ADMIN,
        Roles.PMSMS_USER,
        Roles.PMSMS_ADMIN,
        Roles.PMMOBILE_USER,
        Roles.PMVOICE_USER,
        Roles.PMVOICE_ADMIN,
        Roles.PMMOBILE_ADMIN,
        Roles.EMTIOT_USER,
        Roles.EMTIOT_ADMIN,
        Roles.EMTMOBILE_USER,
        Roles.EMTMOBILE_ADMIN,
        Roles.EMTCFO_USER,
        Roles.EMTCFO_ADMIN,
        Roles.GUEST_USER,
        Roles.DEPLOYMENT_ADMIN,
        Roles.DEPLOYMENT_USER,
      ],
      routePath: '/landing/process/',
      isExactRouteMatch: false,
      itemChildren: [
        {
          itemId: '',
          itemName: 'My queue',
          itemIconClass: 'fa fa-tasks',
          visibleFor: [
            Roles.LEGAL_ADMIN,
            Roles.SUPER_ADMIN,
            Roles.SALES_USER,
            Roles.LEGAL_USER,
            Roles.SYSTEM_ADMIN,
            Roles.BILLING_USER,
            Roles.BILLING_ADMIN,
            Roles.COMMERCIAL_OPS_ADMIN,
            Roles.COMMERCIAL_OPS_USER,
            Roles.CREDIT_ADMIN,
            Roles.CREDIT_USER,
            Roles.FPA_USER,
            Roles.FPA_ADMIN,
            Roles.INTERCONNECT_DESIGN_USER,
            Roles.INTERCONNECT_DESIGN_ADMIN,
            Roles.DEPLOYMENT_ADMIN,
            Roles.DEPLOYMENT_USER,
            Roles.PRODUCT_MANAGEMENT_USER,
            Roles.PRODUCT_MANAGEMENT_ADMIN,
            Roles.PMIOT_USER,
            Roles.PMIOT_ADMIN,
            Roles.PMSMS_USER,
            Roles.PMSMS_ADMIN,
            Roles.PMMOBILE_USER,
            Roles.PMVOICE_USER,
            Roles.PMVOICE_ADMIN,
            Roles.PMMOBILE_ADMIN,
            Roles.EMTIOT_USER,
            Roles.EMTIOT_ADMIN,
            Roles.EMTMOBILE_USER,
            Roles.EMTMOBILE_ADMIN,
            Roles.EMTCFO_USER,
            Roles.EMTCFO_ADMIN,
            Roles.PMGRMOBILE_ADMIN,
            Roles.PMGRMOBILE_USER,
            Roles.EMTSALES_ADMIN,
            Roles.EMTSALES_USER,
          ],
          routePath: '/landing/process/my-queue',
          isExactRouteMatch: true,
        },
        {
          itemId: 'group',
          itemName: 'My group queue',
          itemIconClass: 'fa fa-object-group',
          visibleFor: [
            Roles.LEGAL_ADMIN,
            Roles.LEGAL_USER,
            Roles.BILLING_USER,
            Roles.BILLING_ADMIN,
            Roles.COMMERCIAL_OPS_ADMIN,
            Roles.COMMERCIAL_OPS_USER,
            Roles.CREDIT_ADMIN,
            Roles.CREDIT_USER,
            Roles.FPA_USER,
            Roles.FPA_ADMIN,
            Roles.INTERCONNECT_DESIGN_USER,
            Roles.INTERCONNECT_DESIGN_ADMIN,
            Roles.DEPLOYMENT_ADMIN,
            Roles.DEPLOYMENT_USER,
            Roles.PRODUCT_MANAGEMENT_USER,
            Roles.PRODUCT_MANAGEMENT_ADMIN,
            Roles.PMIOT_USER,
            Roles.PMIOT_ADMIN,
            Roles.PMSMS_USER,
            Roles.PMSMS_ADMIN,
            Roles.PMMOBILE_USER,
            Roles.PMVOICE_USER,
            Roles.PMVOICE_ADMIN,
            Roles.PMMOBILE_ADMIN,
            Roles.EMTIOT_USER,
            Roles.EMTIOT_ADMIN,
            Roles.EMTMOBILE_USER,
            Roles.EMTMOBILE_ADMIN,
            Roles.EMTCFO_USER,
            Roles.EMTCFO_ADMIN,
            Roles.PMGRMOBILE_ADMIN,
            Roles.PMGRMOBILE_USER,
            Roles.EMTSALES_ADMIN,
            Roles.EMTSALES_USER,
          ],
          routePath: '/landing/process/group',
          isExactRouteMatch: true,
        },
        {
          itemId: 'initiate',
          itemName: 'Initiate Contract',
          itemIconClass: 'fa fa-plus-circle',
          visibleFor: [Roles.SALES_USER],
          routePath: '/landing/process/initiate',
          isExactRouteMatch: true,
        },
        // {
        //   itemId: '', itemName: 'My Comments', itemIconClass: 'fa fa-comments-o',
        //   visibleFor: [
        //     Roles.LEGAL_ADMIN, Roles.SUPER_ADMIN, Roles.SALES_USER, Roles.LEGAL_USER, Roles.SYSTEM_ADMIN,
        //     Roles.BILLING_USER, Roles.BILLING_ADMIN, Roles.COMMERCIAL_OPS_ADMIN, Roles.COMMERCIAL_OPS_USER,
        //     Roles.CREDIT_ADMIN, Roles.CREDIT_USER, Roles.FPA_USER, Roles.FPA_ADMIN, Roles.INTERCONNECT_DESIGN_USER,
        //     Roles.INTERCONNECT_DESIGN_ADMIN, Roles.DEPLOYMENT_ADMIN, Roles.DEPLOYMENT_USER, Roles.PRODUCT_MANAGEMENT_USER, Roles.PRODUCT_MANAGEMENT_ADMIN,
        //     Roles.PMIOT_USER, Roles.PMIOT_ADMIN, Roles.PMSMS_USER, Roles.PMSMS_ADMIN, Roles.PMMOBILE_USER, Roles.PMVOICE_USER, Roles.PMVOICE_ADMIN,
        //     Roles.PMMOBILE_ADMIN, Roles.EMTIOT_USER, Roles.EMTIOT_ADMIN, Roles.EMTMOBILE_USER, Roles.EMTMOBILE_ADMIN,
        //     Roles.EMTCFO_USER, Roles.EMTCFO_ADMIN, Roles.PMGRMOBILE_ADMIN, Roles.PMGRMOBILE_USER,
        //     Roles.EMTSALES_ADMIN, Roles.EMTSALES_USER
        //   ],
        //   routePath: '/landing/process/my-comments',
        //   isExactRouteMatch:true
        // },
        {
          itemId: 'contracts',
          itemName: 'All Contracts',
          itemIconClass: 'fa fa-file-text-o',
          visibleFor: [
            Roles.LEGAL_ADMIN,
            Roles.SUPER_ADMIN,
            Roles.SALES_USER,
            Roles.LEGAL_USER,
            Roles.BILLING_USER,
            Roles.BILLING_ADMIN,
            Roles.COMMERCIAL_OPS_ADMIN,
            Roles.COMMERCIAL_OPS_USER,
            Roles.CREDIT_ADMIN,
            Roles.CREDIT_USER,
            Roles.FPA_USER,
            Roles.FPA_ADMIN,
            Roles.INTERCONNECT_DESIGN_USER,
            Roles.INTERCONNECT_DESIGN_ADMIN,
            Roles.DEPLOYMENT_ADMIN,
            Roles.DEPLOYMENT_USER,
            Roles.PRODUCT_MANAGEMENT_USER,
            Roles.PRODUCT_MANAGEMENT_ADMIN,
            Roles.GUEST_USER,
            Roles.PMIOT_USER,
            Roles.PMIOT_ADMIN,
            Roles.PMSMS_USER,
            Roles.PMSMS_ADMIN,
            Roles.PMMOBILE_USER,
            Roles.PMVOICE_USER,
            Roles.PMVOICE_ADMIN,
            Roles.PMMOBILE_ADMIN,
            Roles.EMTIOT_USER,
            Roles.EMTIOT_ADMIN,
            Roles.EMTMOBILE_USER,
            Roles.EMTMOBILE_ADMIN,
            Roles.EMTCFO_USER,
            Roles.EMTCFO_ADMIN,
          ],
          routePath: '/landing/process/contracts',
          isExactRouteMatch: true,
        },
        {
          itemId: 'alltasks',
          itemName: 'All Tasks',
          itemIconClass: 'fa fa-database',
          visibleFor: [
            Roles.LEGAL_ADMIN,
            Roles.SUPER_ADMIN,
            Roles.SALES_USER,
            Roles.LEGAL_USER,
            Roles.BILLING_USER,
            Roles.BILLING_ADMIN,
            Roles.COMMERCIAL_OPS_ADMIN,
            Roles.COMMERCIAL_OPS_USER,
            Roles.CREDIT_ADMIN,
            Roles.CREDIT_USER,
            Roles.FPA_USER,
            Roles.FPA_ADMIN,
            Roles.INTERCONNECT_DESIGN_USER,
            Roles.INTERCONNECT_DESIGN_ADMIN,
            Roles.DEPLOYMENT_ADMIN,
            Roles.DEPLOYMENT_USER,
            Roles.PRODUCT_MANAGEMENT_USER,
            Roles.PRODUCT_MANAGEMENT_ADMIN,
            Roles.GUEST_USER,
            Roles.PMIOT_USER,
            Roles.PMIOT_ADMIN,
            Roles.PMSMS_USER,
            Roles.PMSMS_ADMIN,
            Roles.PMMOBILE_USER,
            Roles.PMVOICE_USER,
            Roles.PMVOICE_ADMIN,
            Roles.PMMOBILE_ADMIN,
            Roles.EMTIOT_USER,
            Roles.EMTIOT_ADMIN,
            Roles.EMTMOBILE_USER,
            Roles.EMTMOBILE_ADMIN,
            Roles.EMTCFO_USER,
            Roles.EMTCFO_ADMIN,
          ],
          routePath: '/landing/process/all-tasks',
          isExactRouteMatch: true,
        },
      ],
    },
    {
      itemId: 'company',
      itemName: 'Company',
      itemIconClass: 'fa fa-building',
      visibleFor: [Roles.SUPER_ADMIN, Roles.SYSTEM_ADMIN, Roles.LEGAL_ADMIN],
      routePath: '/landing/company/',
      isExactRouteMatch: false,
      itemChildren: [
        {
          itemId: 'companies',
          itemName: 'Company Management',
          itemIconClass: 'fa fa-building',
          visibleFor: [
            Roles.SUPER_ADMIN,
            Roles.SYSTEM_ADMIN,
            Roles.LEGAL_ADMIN,
          ],
          routePath: '/landing/company/companies',
          isExactRouteMatch: true,
        },
        {
          itemId: 'contracting-entities',
          itemName: 'Contracting Entities',
          itemIconClass: 'fa fa-life-ring',
          visibleFor: [
            Roles.SUPER_ADMIN,
            Roles.SYSTEM_ADMIN,
            Roles.LEGAL_ADMIN,
          ],
          routePath: '/landing/company/contracting-entities',
          isExactRouteMatch: true,
        },
        {
          itemId: 'country-management',
          itemName: 'Country Management',
          itemIconClass: 'fa fa-globe',
          visibleFor: [
            Roles.SUPER_ADMIN,
            Roles.SYSTEM_ADMIN,
            Roles.LEGAL_ADMIN,
          ],
          routePath: '/landing/company/country-management',
          isExactRouteMatch: true,
        },
      ],
    },
    {
      itemId: 'user-management',
      itemName: 'User Management',
      itemIconClass: 'fa fa-id-badge',
      visibleFor: [Roles.SUPER_ADMIN, Roles.SYSTEM_ADMIN],
      routePath: '/landing/user-management/',
      isExactRouteMatch: false,
      itemChildren: [
        {
          itemId: 'users',
          itemName: 'Users',
          itemIconClass: 'fa fa-users',
          visibleFor: [Roles.SUPER_ADMIN, Roles.SYSTEM_ADMIN],
          routePath: '/landing/user-management/users',
          isExactRouteMatch: true,
        },
        /* {
          itemId: 'groups', itemName: 'Groups', itemIconPath: './assets/images/groups.png',
          visibleFor: [
            Roles.SUPER_ADMIN, 
            Roles.SYSTEM_ADMIN
          ], 
          routePath: '/landing/user-management/groups', 
          isExactRouteMatch:true
        }, */
      ],
    },
    {
      itemId: 'system',
      itemName: 'System',
      itemIconClass: 'fa fa-cogs',
      visibleFor: [Roles.SUPER_ADMIN, Roles.SYSTEM_ADMIN],
      routePath: '/landing/system/',
      isExactRouteMatch: false,
      itemChildren: [
        {
          itemId: 'process-variable',
          itemName: 'Process Variable',
          itemIconClass: 'fa fa-subscript',
          visibleFor: [Roles.SYSTEM_ADMIN],
          routePath: '/landing/system/process-variable',
          isExactRouteMatch: true,
        },
        {
          itemId: 'process-forms',
          itemName: 'Process Forms',
          itemIconClass: 'fa fa-wpforms',
          visibleFor: [Roles.SYSTEM_ADMIN],
          routePath: '/landing/system/process-forms',
          isExactRouteMatch: true,
        },
        {
          itemId: 'reference-data',
          itemName: 'Reference Data',
          itemIconClass: 'fa fa-th',
          visibleFor: [Roles.SUPER_ADMIN, Roles.SYSTEM_ADMIN],
          routePath: '/landing/system/reference-data',
          isExactRouteMatch: true,
        },
        {
          itemId: 'content-management',
          itemName: 'Email Content',
          itemIconClass: 'fa fa-file-text',
          visibleFor: [Roles.SUPER_ADMIN, Roles.SYSTEM_ADMIN],
          routePath: '/landing/system/content-management',
          isExactRouteMatch: true,
        },
      ],
    },
    {
      itemId: 'notifications',
      itemName: 'Notifications',
      itemIconClass: 'fa fa-bell',
      visibleFor: [
        Roles.LEGAL_ADMIN,
        Roles.SUPER_ADMIN,
        Roles.SALES_USER,
        Roles.LEGAL_USER,
        Roles.SYSTEM_ADMIN,
        Roles.BILLING_USER,
        Roles.BILLING_ADMIN,
        Roles.COMMERCIAL_OPS_ADMIN,
        Roles.COMMERCIAL_OPS_USER,
        Roles.CREDIT_ADMIN,
        Roles.CREDIT_USER,
        Roles.FPA_USER,
        Roles.FPA_ADMIN,
        Roles.INTERCONNECT_DESIGN_USER,
        Roles.INTERCONNECT_DESIGN_ADMIN,
        Roles.DEPLOYMENT_ADMIN,
        Roles.DEPLOYMENT_USER,
        Roles.PRODUCT_MANAGEMENT_USER,
        Roles.PRODUCT_MANAGEMENT_ADMIN,
        Roles.PMIOT_USER,
        Roles.PMIOT_ADMIN,
        Roles.PMSMS_USER,
        Roles.PMSMS_ADMIN,
        Roles.PMVOICE_USER,
        Roles.PMVOICE_ADMIN,
        Roles.PMMOBILE_USER,
        Roles.PMMOBILE_ADMIN,
        Roles.EMTIOT_USER,
        Roles.EMTIOT_ADMIN,
        Roles.EMTMOBILE_USER,
        Roles.EMTMOBILE_ADMIN,
        Roles.EMTCFO_USER,
        Roles.EMTCFO_ADMIN,
        Roles.GUEST_USER,
        Roles.PMGRMOBILE_ADMIN,
        Roles.PMGRMOBILE_USER,
        Roles.EMTSALES_ADMIN,
        Roles.EMTSALES_USER,
      ],
      routePath: '/landing/notifications',
      isExactRouteMatch: true,
    },
    {
      itemId: 'dms-link',
      itemName: 'DMS - Historical Contracts',
      itemIconClass: 'fa fa-book',
      visibleFor: [
        Roles.LEGAL_ADMIN,
        Roles.SUPER_ADMIN,
        Roles.SALES_USER,
        Roles.LEGAL_USER,
        Roles.SYSTEM_ADMIN,
        Roles.BILLING_USER,
        Roles.BILLING_ADMIN,
        Roles.COMMERCIAL_OPS_ADMIN,
        Roles.COMMERCIAL_OPS_USER,
        Roles.CREDIT_ADMIN,
        Roles.CREDIT_USER,
        Roles.FPA_USER,
        Roles.FPA_ADMIN,
        Roles.INTERCONNECT_DESIGN_USER,
        Roles.INTERCONNECT_DESIGN_ADMIN,
        Roles.DEPLOYMENT_ADMIN,
        Roles.DEPLOYMENT_USER,
        Roles.PRODUCT_MANAGEMENT_USER,
        Roles.PRODUCT_MANAGEMENT_ADMIN,
        Roles.PMIOT_USER,
        Roles.PMIOT_ADMIN,
        Roles.PMSMS_USER,
        Roles.PMSMS_ADMIN,
        Roles.PMVOICE_USER,
        Roles.PMVOICE_ADMIN,
        Roles.PMMOBILE_USER,
        Roles.PMMOBILE_ADMIN,
        Roles.EMTIOT_USER,
        Roles.EMTIOT_ADMIN,
        Roles.EMTMOBILE_USER,
        Roles.EMTMOBILE_ADMIN,
        Roles.EMTCFO_USER,
        Roles.EMTCFO_ADMIN,
        Roles.GUEST_USER,
        Roles.PMGRMOBILE_ADMIN,
        Roles.PMGRMOBILE_USER,
        Roles.EMTSALES_ADMIN,
        Roles.EMTSALES_USER,
      ],
      isExternalLink: true,
      link: environment.dmslink,
    },
  ];

  sideNavTaiho = [
    {
      itemId: 'process',
      itemName: 'Process Explorer',
      itemIconClass: 'fa fa-pie-chart',
      visibleFor: [
        Roles.LEGAL_ADMIN,
        Roles.SUPER_ADMIN,
        Roles.SALES_USER,
        Roles.LEGAL_USER,
        Roles.SYSTEM_ADMIN,
        Roles.BILLING_USER,
        Roles.BILLING_ADMIN,
        Roles.COMMERCIAL_OPS_ADMIN,
        Roles.COMMERCIAL_OPS_USER,
        Roles.CREDIT_ADMIN,
        Roles.CREDIT_USER,
        Roles.FPA_USER,
        Roles.FPA_ADMIN,
        Roles.INTERCONNECT_DESIGN_USER,
        Roles.INTERCONNECT_DESIGN_ADMIN,
        Roles.PRODUCT_MANAGEMENT_USER,
        Roles.PRODUCT_MANAGEMENT_ADMIN,
        Roles.PMIOT_USER,
        Roles.PMIOT_ADMIN,
        Roles.PMSMS_USER,
        Roles.PMSMS_ADMIN,
        Roles.PMVOICE_USER,
        Roles.PMVOICE_ADMIN,
        Roles.PMMOBILE_USER,
        Roles.PMVOICE_USER,
        Roles.PMVOICE_ADMIN,
        Roles.PMMOBILE_ADMIN,
        Roles.EMTIOT_USER,
        Roles.EMTIOT_ADMIN,
        Roles.EMTMOBILE_USER,
        Roles.EMTMOBILE_ADMIN,
        Roles.EMTCFO_USER,
        Roles.EMTCFO_ADMIN,
        Roles.GUEST_USER,
        Roles.DEPLOYMENT_ADMIN,
        Roles.DEPLOYMENT_USER,
      ],
      routePath: '/landing/process/',
      isExactRouteMatch: false,
      itemChildren: [
        {
          itemId: '',
          itemName: 'My queue',
          itemIconClass: 'fa fa-tasks',
          visibleFor: [
            Roles.LEGAL_ADMIN,
            Roles.SUPER_ADMIN,
            Roles.SALES_USER,
            Roles.LEGAL_USER,
            Roles.SYSTEM_ADMIN,
            Roles.BILLING_USER,
            Roles.BILLING_ADMIN,
            Roles.COMMERCIAL_OPS_ADMIN,
            Roles.COMMERCIAL_OPS_USER,
            Roles.CREDIT_ADMIN,
            Roles.CREDIT_USER,
            Roles.FPA_USER,
            Roles.FPA_ADMIN,
            Roles.INTERCONNECT_DESIGN_USER,
            Roles.INTERCONNECT_DESIGN_ADMIN,
            Roles.DEPLOYMENT_ADMIN,
            Roles.DEPLOYMENT_USER,
            Roles.PRODUCT_MANAGEMENT_USER,
            Roles.PRODUCT_MANAGEMENT_ADMIN,
            Roles.PMIOT_USER,
            Roles.PMIOT_ADMIN,
            Roles.PMSMS_USER,
            Roles.PMSMS_ADMIN,
            Roles.PMMOBILE_USER,
            Roles.PMVOICE_USER,
            Roles.PMVOICE_ADMIN,
            Roles.PMMOBILE_ADMIN,
            Roles.EMTIOT_USER,
            Roles.EMTIOT_ADMIN,
            Roles.EMTMOBILE_USER,
            Roles.EMTMOBILE_ADMIN,
            Roles.EMTCFO_USER,
            Roles.EMTCFO_ADMIN,
            Roles.PMGRMOBILE_ADMIN,
            Roles.PMGRMOBILE_USER,
            Roles.EMTSALES_ADMIN,
            Roles.EMTSALES_USER,
          ],
          routePath: '/landing/process/my-queue',
          isExactRouteMatch: true,
        },
        {
          itemId: 'group',
          itemName: 'My group queue',
          itemIconClass: 'fa fa-object-group',
          visibleFor: [
            Roles.LEGAL_ADMIN,
            Roles.LEGAL_USER,
            Roles.SYSTEM_ADMIN,
            Roles.BILLING_USER,
            Roles.BILLING_ADMIN,
            Roles.COMMERCIAL_OPS_ADMIN,
            Roles.COMMERCIAL_OPS_USER,
            Roles.CREDIT_ADMIN,
            Roles.CREDIT_USER,
            Roles.FPA_USER,
            Roles.FPA_ADMIN,
            Roles.INTERCONNECT_DESIGN_USER,
            Roles.INTERCONNECT_DESIGN_ADMIN,
            Roles.DEPLOYMENT_ADMIN,
            Roles.DEPLOYMENT_USER,
            Roles.PRODUCT_MANAGEMENT_USER,
            Roles.PRODUCT_MANAGEMENT_ADMIN,
            Roles.PMIOT_USER,
            Roles.PMIOT_ADMIN,
            Roles.PMSMS_USER,
            Roles.PMSMS_ADMIN,
            Roles.PMMOBILE_USER,
            Roles.PMVOICE_USER,
            Roles.PMVOICE_ADMIN,
            Roles.PMMOBILE_ADMIN,
            Roles.EMTIOT_USER,
            Roles.EMTIOT_ADMIN,
            Roles.EMTMOBILE_USER,
            Roles.EMTMOBILE_ADMIN,
            Roles.EMTCFO_USER,
            Roles.EMTCFO_ADMIN,
            Roles.PMGRMOBILE_ADMIN,
            Roles.PMGRMOBILE_USER,
            Roles.EMTSALES_ADMIN,
            Roles.EMTSALES_USER,
          ],
          routePath: '/landing/process/group',
          isExactRouteMatch: true,
        },
        {
          itemId: 'initiate',
          itemName: 'Initiate Invoice',
          itemIconClass: 'fa fa-plus-circle',
          visibleFor: [Roles.SALES_USER],
          routePath: '/landing/process/initiate',
          isExactRouteMatch: true,
        },
        // {
        //   itemId: '', itemName: 'My Comments', itemIconClass: 'fa fa-comments-o',
        //   visibleFor: [
        //     Roles.LEGAL_ADMIN, Roles.SUPER_ADMIN, Roles.SALES_USER, Roles.LEGAL_USER, Roles.SYSTEM_ADMIN,
        //     Roles.BILLING_USER, Roles.BILLING_ADMIN, Roles.COMMERCIAL_OPS_ADMIN, Roles.COMMERCIAL_OPS_USER,
        //     Roles.CREDIT_ADMIN, Roles.CREDIT_USER, Roles.FPA_USER, Roles.FPA_ADMIN, Roles.INTERCONNECT_DESIGN_USER,
        //     Roles.INTERCONNECT_DESIGN_ADMIN, Roles.DEPLOYMENT_ADMIN, Roles.DEPLOYMENT_USER, Roles.PRODUCT_MANAGEMENT_USER, Roles.PRODUCT_MANAGEMENT_ADMIN,
        //     Roles.PMIOT_USER, Roles.PMIOT_ADMIN, Roles.PMSMS_USER, Roles.PMSMS_ADMIN, Roles.PMMOBILE_USER, Roles.PMVOICE_USER, Roles.PMVOICE_ADMIN,
        //     Roles.PMMOBILE_ADMIN, Roles.EMTIOT_USER, Roles.EMTIOT_ADMIN, Roles.EMTMOBILE_USER, Roles.EMTMOBILE_ADMIN,
        //     Roles.EMTCFO_USER, Roles.EMTCFO_ADMIN, Roles.PMGRMOBILE_ADMIN, Roles.PMGRMOBILE_USER,
        //     Roles.EMTSALES_ADMIN, Roles.EMTSALES_USER
        //   ],
        //   routePath: '/landing/process/my-comments',
        //   isExactRouteMatch:true
        // },
        {
          itemId: 'contracts',
          itemName: 'All Invoices',
          itemIconClass: 'fa fa-file-text-o',
          visibleFor: [
            Roles.LEGAL_ADMIN,
            Roles.SUPER_ADMIN,
            Roles.SALES_USER,
            Roles.LEGAL_USER,
            Roles.BILLING_USER,
            Roles.BILLING_ADMIN,
            Roles.COMMERCIAL_OPS_ADMIN,
            Roles.COMMERCIAL_OPS_USER,
            Roles.CREDIT_ADMIN,
            Roles.CREDIT_USER,
            Roles.FPA_USER,
            Roles.FPA_ADMIN,
            Roles.INTERCONNECT_DESIGN_USER,
            Roles.INTERCONNECT_DESIGN_ADMIN,
            Roles.DEPLOYMENT_ADMIN,
            Roles.DEPLOYMENT_USER,
            Roles.PRODUCT_MANAGEMENT_USER,
            Roles.PRODUCT_MANAGEMENT_ADMIN,
            Roles.GUEST_USER,
            Roles.PMIOT_USER,
            Roles.PMIOT_ADMIN,
            Roles.PMSMS_USER,
            Roles.PMSMS_ADMIN,
            Roles.PMMOBILE_USER,
            Roles.PMVOICE_USER,
            Roles.PMVOICE_ADMIN,
            Roles.PMMOBILE_ADMIN,
            Roles.EMTIOT_USER,
            Roles.EMTIOT_ADMIN,
            Roles.EMTMOBILE_USER,
            Roles.EMTMOBILE_ADMIN,
            Roles.EMTCFO_USER,
            Roles.EMTCFO_ADMIN,
          ],
          routePath: '/landing/process/contracts',
          isExactRouteMatch: true,
        },
        {
          itemId: 'alltasks',
          itemName: 'All Tasks',
          itemIconClass: 'fa fa-database',
          visibleFor: [
            Roles.LEGAL_ADMIN,
            Roles.SUPER_ADMIN,
            Roles.SALES_USER,
            Roles.LEGAL_USER,
            Roles.BILLING_USER,
            Roles.BILLING_ADMIN,
            Roles.COMMERCIAL_OPS_ADMIN,
            Roles.COMMERCIAL_OPS_USER,
            Roles.CREDIT_ADMIN,
            Roles.CREDIT_USER,
            Roles.FPA_USER,
            Roles.FPA_ADMIN,
            Roles.INTERCONNECT_DESIGN_USER,
            Roles.INTERCONNECT_DESIGN_ADMIN,
            Roles.DEPLOYMENT_ADMIN,
            Roles.DEPLOYMENT_USER,
            Roles.PRODUCT_MANAGEMENT_USER,
            Roles.PRODUCT_MANAGEMENT_ADMIN,
            Roles.GUEST_USER,
            Roles.PMIOT_USER,
            Roles.PMIOT_ADMIN,
            Roles.PMSMS_USER,
            Roles.PMSMS_ADMIN,
            Roles.PMMOBILE_USER,
            Roles.PMVOICE_USER,
            Roles.PMVOICE_ADMIN,
            Roles.PMMOBILE_ADMIN,
            Roles.EMTIOT_USER,
            Roles.EMTIOT_ADMIN,
            Roles.EMTMOBILE_USER,
            Roles.EMTMOBILE_ADMIN,
            Roles.EMTCFO_USER,
            Roles.EMTCFO_ADMIN,
          ],
          routePath: '/landing/process/all-tasks',
          isExactRouteMatch: true,
        },
      ],
    },
    {
      itemId: 'company',
      itemName: 'Company',
      itemIconClass: 'fa fa-building',
      visibleFor: [Roles.SUPER_ADMIN, Roles.LEGAL_ADMIN],
      routePath: '/landing/company/',
      isExactRouteMatch: false,
      itemChildren: [
        {
          itemId: 'companies',
          itemName: 'Company Management',
          itemIconClass: 'fa fa-building',
          visibleFor: [
            Roles.SUPER_ADMIN,
            Roles.SYSTEM_ADMIN,
            Roles.LEGAL_ADMIN,
          ],
          routePath: '/landing/company/companies',
          isExactRouteMatch: true,
        },
        {
          itemId: 'contracting-entities',
          itemName: 'Contracting Entities',
          itemIconClass: 'fa fa-life-ring',
          visibleFor: [
            Roles.SUPER_ADMIN,
            Roles.SYSTEM_ADMIN,
            Roles.LEGAL_ADMIN,
          ],
          routePath: '/landing/company/contracting-entities',
          isExactRouteMatch: true,
        },
        {
          itemId: 'country-management',
          itemName: 'Country Management',
          itemIconClass: 'fa fa-globe',
          visibleFor: [
            Roles.SUPER_ADMIN,
            Roles.SYSTEM_ADMIN,
            Roles.LEGAL_ADMIN,
          ],
          routePath: '/landing/company/country-management',
          isExactRouteMatch: true,
        },
      ],
    },
    {
      itemId: 'user-management',
      itemName: 'User Management',
      itemIconClass: 'fa fa-id-badge',
      visibleFor: [Roles.SUPER_ADMIN, Roles.SYSTEM_ADMIN],
      routePath: '/landing/user-management/',
      isExactRouteMatch: false,
      itemChildren: [
        {
          itemId: 'users',
          itemName: 'Users',
          itemIconClass: 'fa fa-users',
          visibleFor: [Roles.SUPER_ADMIN, Roles.SYSTEM_ADMIN],
          routePath: '/landing/user-management/users',
          isExactRouteMatch: true,
        },
        /* {
          itemId: 'groups', itemName: 'Groups', itemIconPath: './assets/images/groups.png',
          visibleFor: [
            Roles.SUPER_ADMIN, 
            Roles.SYSTEM_ADMIN
          ], 
          routePath: '/landing/user-management/groups', 
          isExactRouteMatch:true
        }, */
      ],
    },
    {
      itemId: 'system',
      itemName: 'System',
      itemIconClass: 'fa fa-cogs',
      visibleFor: [Roles.SUPER_ADMIN, Roles.SYSTEM_ADMIN],
      routePath: '/landing/system/',
      isExactRouteMatch: false,
      itemChildren: [
        {
          itemId: 'process-variable',
          itemName: 'Process Variable',
          itemIconClass: 'fa fa-subscript',
          visibleFor: [Roles.SYSTEM_ADMIN],
          routePath: '/landing/system/process-variable',
          isExactRouteMatch: true,
        },
        {
          itemId: 'process-forms',
          itemName: 'Process Forms',
          itemIconClass: 'fa fa-wpforms',
          visibleFor: [Roles.SYSTEM_ADMIN],
          routePath: '/landing/system/process-forms',
          isExactRouteMatch: true,
        },
        {
          itemId: 'reference-data',
          itemName: 'Reference Data',
          itemIconClass: 'fa fa-th',
          visibleFor: [Roles.SUPER_ADMIN, Roles.SYSTEM_ADMIN],
          routePath: '/landing/system/reference-data',
          isExactRouteMatch: true,
        },
        {
          itemId: 'content-management',
          itemName: 'Email Content',
          itemIconClass: 'fa fa-envelope',
          visibleFor: [Roles.SUPER_ADMIN, Roles.SYSTEM_ADMIN],
          routePath: '/landing/system/content-management',
          isExactRouteMatch: true,
        },
      ],
    },

    {
      itemId: 'notifications',
      itemName: 'Notifications',
      itemIconClass: 'fa fa-bell',
      visibleFor: [
        Roles.LEGAL_ADMIN,
        Roles.SUPER_ADMIN,
        Roles.SALES_USER,
        Roles.LEGAL_USER,
        Roles.SYSTEM_ADMIN,
        Roles.BILLING_USER,
        Roles.BILLING_ADMIN,
        Roles.COMMERCIAL_OPS_ADMIN,
        Roles.COMMERCIAL_OPS_USER,
        Roles.CREDIT_ADMIN,
        Roles.CREDIT_USER,
        Roles.FPA_USER,
        Roles.FPA_ADMIN,
        Roles.INTERCONNECT_DESIGN_USER,
        Roles.INTERCONNECT_DESIGN_ADMIN,
        Roles.DEPLOYMENT_ADMIN,
        Roles.DEPLOYMENT_USER,
        Roles.PRODUCT_MANAGEMENT_USER,
        Roles.PRODUCT_MANAGEMENT_ADMIN,
        Roles.PMIOT_USER,
        Roles.PMIOT_ADMIN,
        Roles.PMSMS_USER,
        Roles.PMSMS_ADMIN,
        Roles.PMMOBILE_USER,
        Roles.PMMOBILE_ADMIN,
        Roles.EMTIOT_USER,
        Roles.EMTIOT_ADMIN,
        Roles.EMTMOBILE_USER,
        Roles.EMTMOBILE_ADMIN,
        Roles.EMTCFO_USER,
        Roles.EMTCFO_ADMIN,
        Roles.GUEST_USER,
        Roles.PMGRMOBILE_ADMIN,
        Roles.PMGRMOBILE_USER,
        Roles.EMTSALES_ADMIN,
        Roles.EMTSALES_USER,
      ],
      routePath: '/landing/notifications',
      isExactRouteMatch: true,
    },
    {
      itemId: 'reports',
      itemName: 'Reports',
      itemIconClass: 'fa fa-file-text',
      visibleFor: [
        Roles.LEGAL_ADMIN,
        Roles.SUPER_ADMIN,
        Roles.SALES_USER,
        Roles.LEGAL_USER,
        Roles.SYSTEM_ADMIN,
        Roles.BILLING_USER,
        Roles.BILLING_ADMIN,
        Roles.COMMERCIAL_OPS_ADMIN,
        Roles.COMMERCIAL_OPS_USER,
        Roles.CREDIT_ADMIN,
        Roles.CREDIT_USER,
        Roles.FPA_USER,
        Roles.FPA_ADMIN,
        Roles.INTERCONNECT_DESIGN_USER,
        Roles.INTERCONNECT_DESIGN_ADMIN,
        Roles.DEPLOYMENT_ADMIN,
        Roles.DEPLOYMENT_USER,
        Roles.PRODUCT_MANAGEMENT_USER,
        Roles.PRODUCT_MANAGEMENT_ADMIN,
        Roles.PMIOT_USER,
        Roles.PMIOT_ADMIN,
        Roles.PMSMS_USER,
        Roles.PMSMS_ADMIN,
        Roles.PMMOBILE_USER,
        Roles.PMMOBILE_ADMIN,
        Roles.EMTIOT_USER,
        Roles.EMTIOT_ADMIN,
        Roles.EMTMOBILE_USER,
        Roles.EMTMOBILE_ADMIN,
        Roles.EMTCFO_USER,
        Roles.EMTCFO_ADMIN,
        Roles.GUEST_USER,
        Roles.PMGRMOBILE_ADMIN,
        Roles.PMGRMOBILE_USER,
        Roles.EMTSALES_ADMIN,
        Roles.EMTSALES_USER,
      ],
      routePath: '/landing/reports',
      isExactRouteMatch: true,
    },

    {
      itemId: 'dms-link',
      itemName: 'DMS - Historical Contracts',
      itemIconClass: 'fa fa-book',
      visibleFor: [
        Roles.LEGAL_ADMIN,
        Roles.SUPER_ADMIN,
        Roles.SALES_USER,
        Roles.LEGAL_USER,
        Roles.SYSTEM_ADMIN,
        Roles.BILLING_USER,
        Roles.BILLING_ADMIN,
        Roles.COMMERCIAL_OPS_ADMIN,
        Roles.COMMERCIAL_OPS_USER,
        Roles.CREDIT_ADMIN,
        Roles.CREDIT_USER,
        Roles.FPA_USER,
        Roles.FPA_ADMIN,
        Roles.INTERCONNECT_DESIGN_USER,
        Roles.INTERCONNECT_DESIGN_ADMIN,
        Roles.DEPLOYMENT_ADMIN,
        Roles.DEPLOYMENT_USER,
        Roles.PRODUCT_MANAGEMENT_USER,
        Roles.PRODUCT_MANAGEMENT_ADMIN,
        Roles.PMIOT_USER,
        Roles.PMIOT_ADMIN,
        Roles.PMSMS_USER,
        Roles.PMSMS_ADMIN,
        Roles.PMMOBILE_USER,
        Roles.PMMOBILE_ADMIN,
        Roles.EMTIOT_USER,
        Roles.EMTIOT_ADMIN,
        Roles.EMTMOBILE_USER,
        Roles.EMTMOBILE_ADMIN,
        Roles.EMTCFO_USER,
        Roles.EMTCFO_ADMIN,
        Roles.GUEST_USER,
        Roles.PMGRMOBILE_ADMIN,
        Roles.PMGRMOBILE_USER,
        Roles.EMTSALES_ADMIN,
        Roles.EMTSALES_USER,
      ],
      isExternalLink: true,
      link: environment.dmslink,
    },
  ];
  sideNavLeaveApplication = [
    {
      itemId: 'process',
      itemName: 'Process Explorer',
      itemIconClass: 'fa fa-pie-chart',
      visibleFor: [
        Roles.LEGAL_ADMIN,
        Roles.SUPER_ADMIN,
        Roles.SALES_USER,
        Roles.LEGAL_USER,
        Roles.SYSTEM_ADMIN,
        Roles.BILLING_USER,
        Roles.BILLING_ADMIN,
        Roles.COMMERCIAL_OPS_ADMIN,
        Roles.COMMERCIAL_OPS_USER,
        Roles.CREDIT_ADMIN,
        Roles.CREDIT_USER,
        Roles.FPA_USER,
        Roles.FPA_ADMIN,
        Roles.INTERCONNECT_DESIGN_USER,
        Roles.INTERCONNECT_DESIGN_ADMIN,
        Roles.PRODUCT_MANAGEMENT_USER,
        Roles.PRODUCT_MANAGEMENT_ADMIN,
        Roles.PMIOT_USER,
        Roles.PMIOT_ADMIN,
        Roles.PMSMS_USER,
        Roles.PMSMS_ADMIN,
        Roles.PMMOBILE_USER,
        Roles.PMVOICE_USER,
        Roles.PMVOICE_ADMIN,
        Roles.PMMOBILE_ADMIN,
        Roles.EMTIOT_USER,
        Roles.EMTIOT_ADMIN,
        Roles.EMTMOBILE_USER,
        Roles.EMTMOBILE_ADMIN,
        Roles.EMTCFO_USER,
        Roles.EMTCFO_ADMIN,
        Roles.GUEST_USER,
        Roles.DEPLOYMENT_ADMIN,
        Roles.DEPLOYMENT_USER,
      ],
      routePath: '/landing/process/',
      isExactRouteMatch: false,
      itemChildren: [
        {
          itemId: '',
          itemName: 'My queue',
          itemIconClass: 'fa fa-tasks',
          visibleFor: [
            Roles.LEGAL_ADMIN,
            Roles.SUPER_ADMIN,
            Roles.SALES_USER,
            Roles.LEGAL_USER,
            Roles.SYSTEM_ADMIN,
            Roles.BILLING_USER,
            Roles.BILLING_ADMIN,
            Roles.COMMERCIAL_OPS_ADMIN,
            Roles.COMMERCIAL_OPS_USER,
            Roles.CREDIT_ADMIN,
            Roles.CREDIT_USER,
            Roles.FPA_USER,
            Roles.FPA_ADMIN,
            Roles.INTERCONNECT_DESIGN_USER,
            Roles.INTERCONNECT_DESIGN_ADMIN,
            Roles.DEPLOYMENT_ADMIN,
            Roles.DEPLOYMENT_USER,
            Roles.PRODUCT_MANAGEMENT_USER,
            Roles.PRODUCT_MANAGEMENT_ADMIN,
            Roles.PMIOT_USER,
            Roles.PMIOT_ADMIN,
            Roles.PMSMS_USER,
            Roles.PMSMS_ADMIN,
            Roles.PMMOBILE_USER,
            Roles.PMVOICE_USER,
            Roles.PMVOICE_ADMIN,
            Roles.PMMOBILE_ADMIN,
            Roles.EMTIOT_USER,
            Roles.EMTIOT_ADMIN,
            Roles.EMTMOBILE_USER,
            Roles.EMTMOBILE_ADMIN,
            Roles.EMTCFO_USER,
            Roles.EMTCFO_ADMIN,
            Roles.PMGRMOBILE_ADMIN,
            Roles.PMGRMOBILE_USER,
            Roles.EMTSALES_ADMIN,
            Roles.EMTSALES_USER,
          ],
          routePath: '/landing/process/my-queue',
          isExactRouteMatch: true,
        },
        {
          itemId: 'group',
          itemName: 'My group queue',
          itemIconClass: 'fa fa-object-group',
          visibleFor: [
            Roles.LEGAL_ADMIN,
            Roles.LEGAL_USER,
            Roles.SYSTEM_ADMIN,
            Roles.BILLING_USER,
            Roles.BILLING_ADMIN,
            Roles.COMMERCIAL_OPS_ADMIN,
            Roles.COMMERCIAL_OPS_USER,
            Roles.CREDIT_ADMIN,
            Roles.CREDIT_USER,
            Roles.FPA_USER,
            Roles.FPA_ADMIN,
            Roles.INTERCONNECT_DESIGN_USER,
            Roles.INTERCONNECT_DESIGN_ADMIN,
            Roles.DEPLOYMENT_ADMIN,
            Roles.DEPLOYMENT_USER,
            Roles.PRODUCT_MANAGEMENT_USER,
            Roles.PRODUCT_MANAGEMENT_ADMIN,
            Roles.PMIOT_USER,
            Roles.PMIOT_ADMIN,
            Roles.PMSMS_USER,
            Roles.PMSMS_ADMIN,
            Roles.PMMOBILE_USER,
            Roles.PMVOICE_USER,
            Roles.PMVOICE_ADMIN,
            Roles.PMMOBILE_ADMIN,
            Roles.EMTIOT_USER,
            Roles.EMTIOT_ADMIN,
            Roles.EMTMOBILE_USER,
            Roles.EMTMOBILE_ADMIN,
            Roles.EMTCFO_USER,
            Roles.EMTCFO_ADMIN,
            Roles.PMGRMOBILE_ADMIN,
            Roles.PMGRMOBILE_USER,
            Roles.EMTSALES_ADMIN,
            Roles.EMTSALES_USER,
          ],
          routePath: '/landing/process/group',
          isExactRouteMatch: true,
        },
        {
          itemId: 'initiate',
          itemName: 'Initiate Leave Approval',
          itemIconClass: 'fa fa-plus-circle',
          visibleFor: [Roles.SALES_USER],
          routePath: '/landing/process/initiate',
          isExactRouteMatch: true,
        },
        // {
        //   itemId: '', itemName: 'My Comments', itemIconClass: 'fa fa-comments-o',
        //   visibleFor: [
        //     Roles.LEGAL_ADMIN, Roles.SUPER_ADMIN, Roles.SALES_USER, Roles.LEGAL_USER, Roles.SYSTEM_ADMIN,
        //     Roles.BILLING_USER, Roles.BILLING_ADMIN, Roles.COMMERCIAL_OPS_ADMIN, Roles.COMMERCIAL_OPS_USER,
        //     Roles.CREDIT_ADMIN, Roles.CREDIT_USER, Roles.FPA_USER, Roles.FPA_ADMIN, Roles.INTERCONNECT_DESIGN_USER,
        //     Roles.INTERCONNECT_DESIGN_ADMIN, Roles.DEPLOYMENT_ADMIN, Roles.DEPLOYMENT_USER, Roles.PRODUCT_MANAGEMENT_USER, Roles.PRODUCT_MANAGEMENT_ADMIN,
        //     Roles.PMIOT_USER, Roles.PMIOT_ADMIN, Roles.PMSMS_USER, Roles.PMSMS_ADMIN, Roles.PMMOBILE_USER, Roles.PMVOICE_USER, Roles.PMVOICE_ADMIN,
        //     Roles.PMMOBILE_ADMIN, Roles.EMTIOT_USER, Roles.EMTIOT_ADMIN, Roles.EMTMOBILE_USER, Roles.EMTMOBILE_ADMIN,
        //     Roles.EMTCFO_USER, Roles.EMTCFO_ADMIN, Roles.PMGRMOBILE_ADMIN, Roles.PMGRMOBILE_USER,
        //     Roles.EMTSALES_ADMIN, Roles.EMTSALES_USER
        //   ],
        //   routePath: '/landing/process/my-comments',
        //   isExactRouteMatch:true
        // },
        {
          itemId: 'contracts',
          itemName: 'All Application',
          itemIconClass: 'fa fa-file-text-o',
          visibleFor: [
            Roles.LEGAL_ADMIN,
            Roles.SUPER_ADMIN,
            Roles.SALES_USER,
            Roles.LEGAL_USER,
            Roles.BILLING_USER,
            Roles.BILLING_ADMIN,
            Roles.COMMERCIAL_OPS_ADMIN,
            Roles.COMMERCIAL_OPS_USER,
            Roles.CREDIT_ADMIN,
            Roles.CREDIT_USER,
            Roles.FPA_USER,
            Roles.FPA_ADMIN,
            Roles.INTERCONNECT_DESIGN_USER,
            Roles.INTERCONNECT_DESIGN_ADMIN,
            Roles.DEPLOYMENT_ADMIN,
            Roles.DEPLOYMENT_USER,
            Roles.PRODUCT_MANAGEMENT_USER,
            Roles.PRODUCT_MANAGEMENT_ADMIN,
            Roles.GUEST_USER,
            Roles.PMIOT_USER,
            Roles.PMIOT_ADMIN,
            Roles.PMSMS_USER,
            Roles.PMSMS_ADMIN,
            Roles.PMMOBILE_USER,
            Roles.PMVOICE_USER,
            Roles.PMVOICE_ADMIN,
            Roles.PMMOBILE_ADMIN,
            Roles.EMTIOT_USER,
            Roles.EMTIOT_ADMIN,
            Roles.EMTMOBILE_USER,
            Roles.EMTMOBILE_ADMIN,
            Roles.EMTCFO_USER,
            Roles.EMTCFO_ADMIN,
          ],
          routePath: '/landing/process/contracts',
          isExactRouteMatch: true,
        },
        {
          itemId: 'alltasks',
          itemName: 'All Tasks',
          itemIconClass: 'fa fa-database',
          visibleFor: [
            Roles.LEGAL_ADMIN,
            Roles.SUPER_ADMIN,
            Roles.SALES_USER,
            Roles.LEGAL_USER,
            Roles.BILLING_USER,
            Roles.BILLING_ADMIN,
            Roles.COMMERCIAL_OPS_ADMIN,
            Roles.COMMERCIAL_OPS_USER,
            Roles.CREDIT_ADMIN,
            Roles.CREDIT_USER,
            Roles.FPA_USER,
            Roles.FPA_ADMIN,
            Roles.INTERCONNECT_DESIGN_USER,
            Roles.INTERCONNECT_DESIGN_ADMIN,
            Roles.DEPLOYMENT_ADMIN,
            Roles.DEPLOYMENT_USER,
            Roles.PRODUCT_MANAGEMENT_USER,
            Roles.PRODUCT_MANAGEMENT_ADMIN,
            Roles.GUEST_USER,
            Roles.PMIOT_USER,
            Roles.PMIOT_ADMIN,
            Roles.PMSMS_USER,
            Roles.PMSMS_ADMIN,
            Roles.PMMOBILE_USER,
            Roles.PMVOICE_USER,
            Roles.PMVOICE_ADMIN,
            Roles.PMMOBILE_ADMIN,
            Roles.EMTIOT_USER,
            Roles.EMTIOT_ADMIN,
            Roles.EMTMOBILE_USER,
            Roles.EMTMOBILE_ADMIN,
            Roles.EMTCFO_USER,
            Roles.EMTCFO_ADMIN,
          ],
          routePath: '/landing/process/all-tasks',
          isExactRouteMatch: true,
        },
      ],
    },
    {
      itemId: 'company',
      itemName: 'Company',
      itemIconClass: 'fa fa-building',
      visibleFor: [Roles.SUPER_ADMIN, Roles.LEGAL_ADMIN],
      routePath: '/landing/company/',
      isExactRouteMatch: false,
      itemChildren: [
        {
          itemId: 'companies',
          itemName: 'Company Management',
          itemIconClass: 'fa fa-building',
          visibleFor: [Roles.SUPER_ADMIN, Roles.LEGAL_ADMIN],
          routePath: '/landing/company/companies',
          isExactRouteMatch: true,
        },
        {
          itemId: 'contracting-entities',
          itemName: 'Contracting Entities',
          itemIconClass: 'fa fa-life-ring',
          visibleFor: [Roles.SUPER_ADMIN, Roles.LEGAL_ADMIN],
          routePath: '/landing/company/contracting-entities',
          isExactRouteMatch: true,
        },
        {
          itemId: 'country-management',
          itemName: 'Country Management',
          itemIconClass: 'fa fa-globe',
          visibleFor: [Roles.SUPER_ADMIN, Roles.LEGAL_ADMIN],
          routePath: '/landing/company/country-management',
          isExactRouteMatch: true,
        },
      ],
    },
    {
      itemId: 'user-management',
      itemName: 'User Management',
      itemIconClass: 'fa fa-id-badge',
      visibleFor: [Roles.SUPER_ADMIN, Roles.SYSTEM_ADMIN],
      routePath: '/landing/user-management/',
      isExactRouteMatch: false,
      itemChildren: [
        {
          itemId: 'users',
          itemName: 'Users',
          itemIconClass: 'fa fa-users',
          visibleFor: [Roles.SUPER_ADMIN, Roles.SYSTEM_ADMIN],
          routePath: '/landing/user-management/users',
          isExactRouteMatch: true,
        },
        /* {
          itemId: 'groups', itemName: 'Groups', itemIconPath: './assets/images/groups.png',
          visibleFor: [
            Roles.SUPER_ADMIN, 
            Roles.SYSTEM_ADMIN
          ], 
          routePath: '/landing/user-management/groups', 
          isExactRouteMatch:true
        }, */
      ],
    },

    {
      itemId: 'system',
      itemName: 'System',
      itemIconClass: 'fa fa-cogs',
      visibleFor: [Roles.SUPER_ADMIN, Roles.SYSTEM_ADMIN],
      routePath: '/landing/system/',
      isExactRouteMatch: false,
      itemChildren: [
        {
          itemId: 'process-variable',
          itemName: 'Process Variable',
          itemIconClass: 'fa fa-subscript',
          visibleFor: [Roles.SUPER_ADMIN, Roles.SYSTEM_ADMIN],
          routePath: '/landing/system/process-variable',
          isExactRouteMatch: true,
        },
        {
          itemId: 'process-forms',
          itemName: 'Process Forms',
          itemIconClass: 'fa fa-wpforms',
          visibleFor: [Roles.SUPER_ADMIN, Roles.SYSTEM_ADMIN],
          routePath: '/landing/system/process-forms',
          isExactRouteMatch: true,
        },
        {
          itemId: 'reference-data',
          itemName: 'Reference Data',
          itemIconClass: 'fa fa-th',
          visibleFor: [Roles.SUPER_ADMIN, Roles.SYSTEM_ADMIN],
          routePath: '/landing/system/reference-data',
          isExactRouteMatch: true,
        },
        {
          itemId: 'content-management',
          itemName: 'Email Content',
          itemIconClass: 'fa fa-file-text',
          visibleFor: [Roles.SUPER_ADMIN, Roles.SYSTEM_ADMIN],
          routePath: '/landing/system/content-management',
          isExactRouteMatch: true,
        },
      ],
    },
    {
      itemId: 'notifications',
      itemName: 'Notifications',
      itemIconClass: 'fa fa-bell',
      visibleFor: [
        Roles.LEGAL_ADMIN,
        Roles.SUPER_ADMIN,
        Roles.SALES_USER,
        Roles.LEGAL_USER,
        Roles.SYSTEM_ADMIN,
        Roles.BILLING_USER,
        Roles.BILLING_ADMIN,
        Roles.COMMERCIAL_OPS_ADMIN,
        Roles.COMMERCIAL_OPS_USER,
        Roles.CREDIT_ADMIN,
        Roles.CREDIT_USER,
        Roles.FPA_USER,
        Roles.FPA_ADMIN,
        Roles.INTERCONNECT_DESIGN_USER,
        Roles.INTERCONNECT_DESIGN_ADMIN,
        Roles.DEPLOYMENT_ADMIN,
        Roles.DEPLOYMENT_USER,
        Roles.PRODUCT_MANAGEMENT_USER,
        Roles.PRODUCT_MANAGEMENT_ADMIN,
        Roles.PMIOT_USER,
        Roles.PMIOT_ADMIN,
        Roles.PMSMS_USER,
        Roles.PMSMS_ADMIN,
        Roles.PMMOBILE_USER,
        Roles.PMMOBILE_ADMIN,
        Roles.EMTIOT_USER,
        Roles.EMTIOT_ADMIN,
        Roles.EMTMOBILE_USER,
        Roles.EMTMOBILE_ADMIN,
        Roles.EMTCFO_USER,
        Roles.EMTCFO_ADMIN,
        Roles.GUEST_USER,
        Roles.PMGRMOBILE_ADMIN,
        Roles.PMGRMOBILE_USER,
        Roles.EMTSALES_ADMIN,
        Roles.EMTSALES_USER,
      ],
      routePath: '/landing/notifications',
      isExactRouteMatch: true,
    },
  ];
}
